<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1400" started-at="2020-02-07T07:53:24Z" finished-at="2020-02-07T07:53:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1400" started-at="2020-02-07T07:53:24Z" finished-at="2020-02-07T07:53:26Z">
      <class name="HttpMethodTetscases.PostMethodwithheadersTestcases">
        <test-method status="PASS" signature="setup()[pri:0, instance:HttpMethodTetscases.PostMethodwithheadersTestcases@2b98378d]" name="setup" is-config="true" duration-ms="6" started-at="2020-02-07T13:23:24Z" finished-at="2020-02-07T13:23:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="postMethodtestcaseswithoutheader()[pri:0, instance:HttpMethodTetscases.PostMethodwithheadersTestcases@2b98378d]" name="postMethodtestcaseswithoutheader" duration-ms="1375" started-at="2020-02-07T13:23:24Z" finished-at="2020-02-07T13:23:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [nilesh] but found [mukund]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [nilesh] but found [mukund]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at HttpMethodTetscases.PostMethodwithheadersTestcases.postMethodtestcaseswithoutheader(PostMethodwithheadersTestcases.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postMethodtestcaseswithoutheader -->
      </class> <!-- HttpMethodTetscases.PostMethodwithheadersTestcases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
